name: benchmark_generator
publish-to: none
environment:
  sdk: ^3.7.0-157.0.dev
resolution: workspace

dependencies:
  package_config:

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.7
